server {
    listen 8080;
    server_tokens off;

    location /healthz {
        return 200 "ok";
        add_header Content-Type text/plain;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
